### ISSUE TITLE
libavutil/audioconvert.h is no more!?

### ISSUE THREAD

**Issue by MaverickTse** [VFR-maniac/L-SMASH-Works#38]
While trying to build the plugin for AviUtl, the following error comes up:

../common/libavsmash.c:35:36: fatal error: libavutil/audioconvert.h: No such file or directory

Looking at the FFmpeg GitHub repo, indeed that header disappeared.

**Comment by VFR-maniac** [comment]
Done. ad4bc4750b89a136c70ef0957552ee4320adb2d4

**Comment by MaverickTse** [comment]
Confirmed.
Now builds successfully.
