### ISSUE TITLE
VapourSynth: The field order frame property is wrong

### ISSUE THREAD

**Issue by mawen1250** [VFR-maniac/L-SMASH-Works#41]
_FieldBased  should be 1 for BFF and 2 for TFF.

**Comment by VFR-maniac** [comment]
https://github.com/VFR-maniac/L-SMASH-Works/commit/98478eb8e08cb972fe5454cec5ea3173cbc750e6
I can't what you say. Please speak Japanese, OK?

**Comment by mawen1250** [comment]
OK, then it's already fixed.
