### ISSUE TITLE
LWLibavVideoSource frame synch issues for different formats

### ISSUE THREAD

**Issue by estevaocm** [VFR-maniac/L-SMASH-Works#49]
Hello, thank you for sharing your work!

I've been using LSMASHVideoSource and LWLibavVideoSource with LAV decoders on Windows for comparing video encodes with PSNR, SSIM etc. and have found anomalies which I believe to be due to frame synchronization. I am using the DLLs provided by MeGUI.

Here is my comparison setup:
1) A qp=0 mp4/x264 reference version decoded with LSMASHVideoSource;
2) A 0.072 bpp mp4/x264 version decoded with LSMASHVideoSource;
3) A 0.072 bpp webm/vp8 version decoded with LWLibavVideoSource;
4) A 0.072 bpp avi/xvid version decoded with LWLibavVideoSource;
5) A 0.072 bpp ogv/theora version decoded with LWLibavVideoSource;
6) A 0.072 bpp mp4/x265 version decoded with LSMASHVideoSource;
7) A 0.072 bpp webm/vp9 version decoded with LWLibavVideoSource.

In most versions, I force FPS as such:
LWLibavVideoSource("vp8.webm", fpsnum=24000, fpsden=1001).AssumeFPS(24000,1001)

However, when FPS is forced for webm (either vp8 or vp9) or avi/xvid, something goes horribly wrong and PSNR drops from 42db to 20db; they work well without specifying FPS, though. Inversely, when I don't force FPS for ogv/theora, PSNR drops from 30db to 14db. Whereas LSMASHVideoSource always works correctly with mp4, with or without forcing FPS. DirectShowSource displays the same anomaly for webm, but not for avi.

I was using the build of 2015-10-29. Today I switched to the newer 2016-03-02 (r859). Now, LWLibavVideoSource never works correctly with avi/xvid and I am forced to use DirectShowSource, which for this kind of file works with and without forcing FPS. Before this new issue, I was unsure if the problem was L-Smash or the LAV decoders.

I realize this may be an error on the part of whomever compiles the MeGUI DLLs, but it is my understanding that software is built by experts such as youself, so I think it may be worthwile for you to look into this.

Thank you for your time.

**Comment by VFR-maniac** [comment]
Why don't you use the latest (in rev875 or so) ? Recently, I changed algorithms of the frame identification and it broke seek for packed bitstream which is a hack for B-frames in AVI. And I fixed the break from rev872 to rev874 commits.

About VPx-in-WebM, L-SMASH Works currently uses the repeat control implicitly and internally because of invisible frames (alt-ref frames which are decoded but not displayed) and it is exclusive with VFR->CFR conversion.

**Comment by estevaocm** [comment]
Oh, I assumed there were no official builds and was lazy to compile, but after you asked I've found the DropBox directory linked at the AviSynth wiki. AVI works correctly now, as long as I don't force FPS.

So, the old packed bitstream hack and the golden/alternate frames are the reason VFR is necessary for XviD and VPX? Makes sense, nice to know. Just retested with 877 and everything works as expected.

Thanks again, cheers from Brazil!
