### ISSUE TITLE
Index file is wrong when parsing broken GOP of MPEG-2 Video.

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#60]
L-SMASH Works(のコード)はバグっていませんが、L-SMASH Worksバグってる報告です。

【概要】
MPEG-2 Transport Streamの先頭に破損GOP扱いとなるMPEG-2 Videoが存在、これを扱う際、
インデックスファイル(.lwi)を正しい情報で生成できていない。

バグ動作： リピート制御有効時に「フレーム数」「平均フレームレート値」が正しくない状態となる

※ 録画したTSデータをそのまま編集しようとする人がこれに遭遇（高確率）
※ 「L-SMASH... はフレームレートが～」と言われた場合はこの現象に該当した物と思われる

[以下、前提]
破損GOP＝MPEG-1/2 VideoのGOP先頭にあるシーケンスヘッダが不足しているPicture部位
（GOP単位で扱うソフトであれば捨てる部分）

【原因】
破損GOP部位に libavformat/libavcodec のパース処理を通しても、（シーケンスヘッダがない為）
AVCodecParserContext上の情報はインデックス生成処理に必要な情報が未解析な状態となる。

具体的には pkt_ctx->ticks_per_frame が初期値(1)のまま。
この値はシーケンスヘッダを解析しMPEG-2 Videoと判定されると(2)に設定される。
(libavcodec/mpegvideo_parser.c 参照)

この為、以下の判定が誤動作し破損GOP部位の repeat_pict の値が正しくない値(+)で出力されている。

lwindex.c(2064-2067)

> ```
>                if( pkt_ctx->ticks_per_frame == 2 && helper->parser_ctx->repeat_pict != 0 )
>                    repeat_pict = helper->parser_ctx->repeat_pict;
>                else
>                    repeat_pict = 2 * helper->parser_ctx->repeat_pict + 1;
> ```

結果、リピート制御有効時にフレーム数が水増しされる事になる。
・リピート制御不要なデータ(60iインターレースフレームonly)はリピート制御をオフに設定すれば回避可能
・RFFを含むデータは回避不可能

現状、GOP単位でカット編集するソフト等で前処理を行い、破損GOPを捨てた状態にしないとバグ回避は難しい。
（※RFFを含むデータをカット編集する時には気を付けた方が良い事がいろいろ存在するが、これは別途どこかで明記しておきたい）

【対策案】
maki-rxrz / fix ブランチを参照。
https://github.com/maki-rxrz/L-SMASH-Works/commit/d455411c38382b51f84b124034587239e79b3876

Workaroundになるが、get_index_helper() 内でMPEG-2 Videoでの初期値設定を追加。
（本対応時には INDEX_FILE_VERSION の更新も忘れずに。）

**Comment by maki-rxrz** [comment]
【余談】
以下、libavformat/libavcodec のパース処理を確認していた事で気づいた点。

lwindex.c(2043-2044)
>                if( helper->parser_ctx->picture_structure == AV_PICTURE_STRUCTURE_TOP_FIELD
>                 || helper->parser_ctx->picture_structure == AV_PICTURE_STRUCTURE_BOTTOM_FIELD )

このコードで参照する picture_structure に関して。

libavcodec/mpegvideo_parser.c のパース処理は picture_structure に値を設定していない。
MPEG-2 Videoの規格上は picture_structure の情報が存在し field structure / frame structure を扱うケースが存在する。
（libavcodec/mpeg12dec.c のデコード周りはこれを扱うので必要なら参照）

L-SMASH Works該当コードの処理は現状の libavformat/libavcodec の返す情報から
MPEG-2 Videoは全て frame coded picture の処理で扱うことになる。

現状処理でバグにつながる事はなさそうではあるが、この辺はどう見るべきか？
（H.264などの様に field/frame で処理分けできてる方が良いかどうか、等）

又、MPEG-2 Videoのパース処理を拡張する場合はこんな感じだと思うが、
field structure なデータを未所持の為、動作は未確認。
https://gist.github.com/maki-rxrz/5a7a2c789e4369fa34853b5358fb8a29


余談おわり。

**Comment by VFR-maniac** [comment]
いつもありがとうございます。
field codedなMPEG-2 Videoは知っていましたが、私もそのようなデータを見たことが無いです。
parserに関しては、libavにパッチ送るべきなんですかねぇ。

**Comment by maki-rxrz** [comment]
「データがないといったな、あれは嘘だ」（さーせん

まるも氏のm2v.vfp更新を確認し、手持ちのCS放送のサンプルに対象データがあったので動作確認しました。

既存のlibavformat/libavcodecのパース処理のままだと、lwiファイル上の field order 情報に
order逆転箇所(※最新修正前のDGIndexと同じ)が存在する事を確認できました。
私の書いたパッチを入れる事で field structure を検出し field order を正しく取り扱えるようになる事も確認済みです。

libavcodecのMPEG-2 Videoのデコード処理は、改めてヘッダのパース処理を行い field structure(T/B) と判定した上で処理している為、ユーザーレベルでは影響のない変更になると思われますが、lwiファイルも正しい情報で生成された方が良いと思われます。

【追伸】
gistを更新していますが、別の問題を検証する為のパッチ追加を行った為でこちらはまだ検証を終えていない代物です。（パッチを分けて登録しているので見ればわかると思いますが、念の為）

**Comment by VFR-maniac** [comment]
picture_structureのパッチですが、field structure pictureの時はrepeat_pictを0にしなければいけないのではないでしょうか？

```
                        switch (picture_structure) {
                        case PICT_TOP_FIELD:
                            s->picture_structure = AV_PICTURE_STRUCTURE_TOP_FIELD;
                            s->repeat_pict = 0;
                            break;
                        case PICT_BOTTOM_FIELD:
                            s->picture_structure = AV_PICTURE_STRUCTURE_BOTTOM_FIELD;
                            s->repeat_pict = 0;
                            break;
                        case PICT_FRAME:
                            s->picture_structure = AV_PICTURE_STRUCTURE_FRAME;
                            break;
                        }
```

それと、mpeg12dec.cの方はrepeat_pictの値が+1ずれてるように思います。

**Comment by VFR-maniac** [comment]
... ひょっとして、libavformat, field coded picture 1組を1パケットで返してて、頭のfield coded pictureしか返してないです...？

**Comment by maki-rxrz** [comment]
放置状態にしててスミマセン。
field structure を検証する機会があったので、更新。

----
> ... ひょっとして、libavformat, field coded picture 1組を1パケットで返してて、頭のfield coded pictureの情報しか返してないです...？

はい。libavformat が、というよりも、(MPEG-TS内の)PESパケットには2フィールド分のpictureデータが格納されている様です。

PESパケットに格納された状態、及びDemuxして抽出したESデータのどちらを扱った場合も、
MPEG-2 Videoのデコード処理は2フィールド分のデータから1フレームを構築して返す様になっています。

libavformat で取得できる情報もフレーム単位で扱われているので
repeat_pict の値を更新(0へ設定)する処理は不要です。やるとリピート制御がバグります。

----
> それと、mpeg12dec.cの方はrepeat_pictの値が+1ずれてるように思います。

これ、リピート制御のコードを書いた時にも気になった点でしたが、
当時から libavformat と libavcodec で repeat_pict の扱い方が異なってる様に見受けられました。
正直なところ、私には理由が全くわかっていません。

----
なお改めて動作検証してみた所、発生する不具合動作は先頭フィールド補正の誤爆だけでなく、
フレームレートの誤判定が発生する事を確認しました。

このIssueは元々別件でしたので一旦Closeし、内容を整理した上で新規に登録する事にします。
