### ISSUE TITLE
format option RGB48 support issue in vapoursynth.

### ISSUE THREAD

**Issue by fuchanghao** [VFR-maniac/L-SMASH-Works#61]
L-SMASH-Works-r903-20160815

When I use sth like it

src = core.lsmas.LWLibavSource(video.mkv,format="RGB48")

it showed this error.

[swscaler @ 000000ce71986620] gbrp16le is not supported as output pixel format
Error: Failed to retrieve frame 0 with error: lsmas: failed to output a video frame.

But when use sth like

src = core.lsmas.LWLibavSource(video.mkv,format="RGB30")
src = core.lsmas.LWLibavSource(video.mkv,format="YUV444P16")

it worked.

**Comment by VFR-maniac** [comment]
https://github.com/FFmpeg/FFmpeg/blob/1e660fe88d2dd8fdcb0136b4cee3152f61ebc6c5/libswscale/utils.c#L229
hmmm... I didn't know swscale has no supports of some planar RGB pixel formats for output. Please harass ffmpeg or libav developers. I don't wanna write RGB48 ->planar GBRP16 conversion.

**Comment by VFR-maniac** [comment]
Hi. ffmpeg now supports GPR(A)P16 output, and it should work if compiled by the latest master.

**Comment by fuchanghao** [comment]
Still it doesn't set proper "_Matrix" property on format conversion.
