### ISSUE TITLE
lwinput: Fix high bit-depth input & script input

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#62]
http://echo.2ch.net/test/read.cgi/avi/1252765934/554-555
の報告への修正パッチを2点。

----
1つ目。High bit-depth入力。

https://github.com/VFR-maniac/L-SMASH-Works/commit/8e5fdf0bf30ecd5005c515da241e5e5903fbf373
https://github.com/VFR-maniac/L-SMASH-Works/commit/f9303551ab2791519f0889980df9d6b7510291a2
https://github.com/VFR-maniac/L-SMASH-Works/commit/c732fe9925f7ac67cd3af70f3d36ae29ef6160d7

チラ見した感じ、この辺りの avs_input.c への変更における更新漏れでしょうか。
https://github.com/maki-rxrz/L-SMASH-Works/commit/fbae923b7ae42ce98769e6d6e0151e39c9e6d689

----
2つ目。Doom9で公開されてるバイナリ(※FFmpeg/Libavに --enable-avisynth を使用)での動作に関して。

入力avsの内容次第で下記の2パターンの動作が確認できます。

[Video+Audio]
　AVS Reader が映像と音声の両方を読み込み、open処理が完了。
[Video only/Audio only]
　AVS Reader が読み込めなかった方を別Readerが読めるか(存在するか)を確認する為に別Readerのopen処理を継続試行、avisynth入力機能が有効なlibavformatをリンクした LW+Libav Reader がindexファイルが生成。

(--enable-avisynth 使うなよ、というのは置いておいて、)
まず、専用Readerによって読み込めた時点でVideo/Audioの有無も判断できていると考えられます。そこを踏まえて、indexファイル生成が実行されてしまう(=index云々に関わらず不要な処理を実行している)のはちょっと宜しくないかなと思ったので、下記の様なパッチを書いてみました。

avs/vpyの様なスクリプトタイプのReaderを使用する際、不要と判断できる処理(読み込み・解析)を実行させない様に以下の様な処理を追加。
-> 該当のReaderで、Videoを読み込めたらAudioの有無に関わらずopen処理を完了
-> 該当のReaderで、Audioのみ読み込めたらDummyReader以外のopen処理をスキップ
https://github.com/maki-rxrz/L-SMASH-Works/commit/18627fc35ab6ce3d744c515b00ec4d9b044cf853

----
確認、及び検討の程、宜しくお願いします。

**Comment by VFR-maniac** [comment]
51f0d138dcb55a05f4d41b810334325895b04bea
48db70437bae620ba3a317c4575f925f54f57e85
Applied. Thank you.
