### ISSUE TITLE
lwinput: Fix RGB input

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#63]
http://echo.2ch.net/test/read.cgi/avi/1252765934/389
＞ L-SMASH WorksでRGBのavsを読むと上下反転してしまう

コレに対する修正パッチの様な物です。
間違ってる点があったらRejectして下さい。
https://github.com/maki-rxrz/L-SMASH-Works/commit/460ba49ea46fe7f72c3b38ba2588bd4302fe61d1

確認の程、宜しくお願いします。

**Comment by VFR-maniac** [comment]
これって packedなRGBではなくpackedなBGRの時に起きるってことなのでしょうか？
packed RGB系はボトムアップでpacked BGR系はトップダウン？

**Comment by maki-rxrz** [comment]
スミマセン、私がそのように勘違いしてやってました。
このパッチは根本的な修正になってなかったです。

AviSynthのRGB(BGR)データならストレートに渡せばよいのでは？との思い込みがあって出力処理にばかり目がいってました。修正すべきだったのはavsreader専用のコードです。

[修正]
avs_input.c/read_video() での入力データ(RGB)の参照設定を出力設定と同順に設定。
https://github.com/maki-rxrz/L-SMASH-Works/commit/427e3d9299ecff12302dc5f316a4bee0d2b9393e

確認の程、宜しくお願いします。

**Comment by VFR-maniac** [comment]
Applied a1a280b94ffff9e2ca5b72db7061290f9ca0a6ec .
Thanks!
