### ISSUE TITLE
vslsmashsource: Fix memory leak.

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#65]
【概要】
vslsmashsourceを使用してファイル読み込みを行うと、解放時にメモリーリークが発生する。

※ 最新のVapourSynthではメモリー管理が拡張され、コア解放時にメモリーリーク検出のログが出力されます

【原因】
https://github.com/VFR-maniac/L-SMASH-Works/commit/6bee4871323e15aad3431df40dab8bee46499a1e

このコミットで実装されたprivate_handlerの解放処理(vs_free_video_output_handler)が
それ以前の関数登録処理を削除し忘れている為に実行されていません。

vslsmashsource自体のリークサイズは background_frame の1Frame分(HDサイズで数MB)ですが、
VS側のメモリ管理が確保している1プール分(約100MB程度)が未解放となるので、
VapourSynth EditorやAvsPModなどの編集ソフトでプレビューをON/OFFするとメモリ使用量がガンガン増えていきます。

【修正】
不要な処理を削除。
https://github.com/maki-rxrz/L-SMASH-Works/commit/75b363fc1528e62709e9e801c79e66a00166a1c7

確認の程、よろしくお願いします。

**Comment by VFR-maniac** [comment]
c79971bcc627a559cfaba2c7f7c2adea7094f6e4
Applied. Thanks!
