### ISSUE TITLE
lwindex: Infinite loop issue when parsing sub track audio

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#67]
2chやPOPn氏のサイト(http://pop.4-bit.jp/?page_id=7929 ) に報告されてる現象に関して。
（音声周りのトラブルは他にもあるようですが、本件は再現性100%の物を）
状況確認した内容をIssues上に報告しておきます。

----
【不具合】
副音声付番組を含むMPEG-2 TSを解析する際に、前番組(主)→次番組(主+副)へ切り替わる箇所でindex生成処理がフリーズする。

【原因】
lwindex.c/get_audio_frame_length() 内にて、
副音声が検出された際の helper->decode() (=decode_audio_packet()) のデコード結果が consumed_bytes=0 になる為、該当箇所のwhile文で無限ループに陥る。

【補足】
以下、ユーザーが行える対処方法。

1) ファイル先頭の録画マージンを削る
具体的にはマージン分を 3,4 GOP(≒1.5秒)程度 まで削ると正常にindex処理を完了させる事ができる。
（EITの番組情報的にも前番組の範囲でOK）
※ 全部の放送局を確認してないが、放送局云々は関連しない内容であり、現象の発生するファイル全般で有効と思われる

2) [暫定]コードに手を加えてフリーズ現象を回避
lwindex.c(1784):
  if( consumed_bytes < 0 )
    ↓↓↓
  if( consumed_bytes <= 0 )
※ フリーズさせない為の暫定処置であり、副音声は正しく扱えない

----
とりあえず処理を追っかけて確認したのはここまで。

**Comment by VFR-maniac** [comment]
decode_audio_packet()が0を返すパターンがいくつか考えられるので、
```
if( consumed_bytes <= 0 )
```
にするというのは、無限ループを修正出来たとして、これだけの情報では新たにエンバグをする可能性が払拭できないので、なんともしがたいです。(無限ループはわかりやすいが、こっちは気付きにくいかもしれない)
もうちょっと詳しい状況教えてもらえますか。

現在のdecode_audio_packet()が0を返すパターンは
1. pkt==NULL (flush時だが、今回はこの条件にあてはまらないのは自明)
2. avcodec_send_packet()がEOFやEAGAINを返す
3. pkt->size == 0 (libavformatの仕様上、side-dataだけ伝送する0-size packetも有りうる)
です。(2.だと予想していますが)
また、この時のgot_frameの値やav_frameの値がどうなってるかも気になります。

**Comment by VFR-maniac** [comment]
やはり `2.` のようでした。
何故か、send/receive両方でEOF判定されているため、デコードもできず何も情報が取得できないです。
一応、無限ループの修正を次のように行えば副作用も無く良さそうですが(返り値が正、すなわちsendに成功、またはデコーダが出力、すなわちreceiveが成功ならループを回す)、副音声トラックは正しくインデックス処理できない状態です。
https://gist.github.com/VFR-maniac/6d3ea28241e344f11ccb9e5825936ffa
追って、詳しくデコーダの挙動を見てみます。

**Comment by VFR-maniac** [comment]
2f9d49914f42c2ffe62a9fc20b48de4d3657ffd9
修正しました。どうやら、extradata生成のところで既にデコードしていて、そこでnullパケット投げつけていたため、draining modeが発動して、EOFになっていました。avcodec_flush_buffer()でリセットすることで、ある程度は正しくindexが処理できるようになりました。(エラーハンドリングがまだアレですが。例えば、EAGAIN, EOF以外のエラーを返した時、delayとして扱うかどうか等)

それと、副音声を指定してもトラックを開く時に正しく初期化されていない為、指定した音声トラックを開くのに失敗するようです。映像トラックと同様に初期化値をindexをparseする時に予め取得しておかないとダメですね...
