### ISSUE TITLE
L-smash  doesn't set proper "_Matrix" property on format conversion.

### ISSUE THREAD

**Issue by fuchanghao** [VFR-maniac/L-SMASH-Works#68]
a = r"F:\遊魂 2 -you're the only one- 遊戲開場動畫（中文字幕版）.mp4"
core.lsmas.LWLibavSource(a,threads = 1,format = "RGB24")

When use sth like this didn't set the vapuoursynth's "_Matrix" property.

**Comment by VFR-maniac** [comment]
?
Matrix coefficients are determined when converting RGB->YUV and are used for YUV->RGB conversion to restore RGB. It makes no sense to RGB clip though MPEG coding points have the value 0 for BGR even if RGB.

**Comment by fuchanghao** [comment]
http://www.vapoursynth.com/doc/apireference.html

the _Matrix and _ColorRange should be set after the format conversion.

Sth like，the int number means the format of the _Matrix or _ColorRange.

```
const VSFrameRef * src;
VSMap * props = vsapi->getFramePropsRW(src);
vsapi->propSetInt(props, "_Matrix", 1, paReplace);
vsapi->propSetInt(props, "_ColorRange", 0, paReplace);
```

**Comment by VFR-maniac** [comment]
What is your problem. You specified RGB24 as the output format. For RGB clip, _Matrix is always implied to the value 0 and _ColorRange is not defined.

**Comment by fuchanghao** [comment]
> a = r"F:\遊魂 2 -you're the only one- 遊戲開場動畫（中文字幕版）.mp4"
> core.lsmas.LWLibavSource(a,threads = 1,format = "RGB48")

When using sth like this it is will makes the pewview broken.

```
Error on frame 0 request:
Resize error 1026: RGB color family cannot be YUV
Error on frame 1728 request:
Resize error 1026: RGB color family cannot be YUV
```

Platfrom:
vapoursynth r35
VS Editor r12
L-SMASH-Works-r918-20161205-64bit

Video Clip:
https://www.youtube.com/watch?v=GrPg3fNvRMQ
DDL: https://mega.nz/#!UAwngb4R!UWIodtE13GDxMjPtiQKD3szbEo9hzD5UtJ460qa2gYY

**Comment by VFR-maniac** [comment]
4d0f7afa6f84c92b471f78a8f9789f8894ad22c1 should fix your issue.
I was confused because you said "_Matrix" property isn't set, but "_Matrix" was set to one of the decoded frame not the output frame.
