### ISSUE TITLE
AviUtl/lwmuxer issue: Mismatch of character code.

### ISSUE THREAD

**Issue by maki-rxrz** [VFR-maniac/L-SMASH-Works#72]
POP氏のサイトで報告があった不具合の修正です。

http://pop.4-bit.jp/?page_id=7929&cpage=5#comment-581
＞ L-SMASH Works Muxerでエクスポートするときにファイル名に日本語を使用すると文字化けする

L-SMASHにWindows環境下におけるUnicode対策が導入された以降、同ライブラリの関数に渡す文字列はUTF-8とする事が明示(lsmash.hに記載)されていますが、L-SMASH Worksの lwmuxer.auf のコードにて対応が漏れています。

https://github.com/maki-rxrz/L-SMASH-Works/commit/fce108221a7f0fb6932c8e372dc6025fe001be03

・文字列バッファのサイズは「MAX_PATH」->「MAX_PATH * 4」に変更
　⇒ フルパスを扱う様だったのでもう少し大きい方が良いのかな？が理由
　　「* 4」はchikuzen氏のffmpegでの対策を参考にした値
・変換処理及び結果判定を出力ファイル準備時のifに追加
 ⇒ エラーダイアログを出る方が良いかな？と、エラーメッセージの文言的にココにしてみました

ご確認の程、宜しくお願いします。

**Comment by VFR-maniac** [comment]
Applied thanks. 0eccfd5d0df85215bbbc9c5dd8b466e7450074a1
